FROM maven:3.8.5-jdk-11 AS build
WORKDIR /Backend
COPY pom.xml .
COPY src/ ./src
RUN mvn package -Dmaven.test.skip=true


FROM openjdk:11.0-jdk
VOLUME /tmp
COPY --from=build Backend/target/Backend-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]